/*
 * Nile API
 *
 * Making SaaS chill.
 *
 * The version of the OpenAPI document: 0.1.0-fdd7cd5
 * Contact: support@thenile.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Bucket {
    /// The timestamp when the bucket starts
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    /// The size of the bucket
    #[serde(rename = "bucket_size", skip_serializing_if = "Option::is_none")]
    pub bucket_size: Option<BucketSize>,
    /// The average of all values in the bucket
    #[serde(rename = "average", skip_serializing_if = "Option::is_none")]
    pub average: Option<f64>,
    /// The sum of all values in the bucket
    #[serde(rename = "sum", skip_serializing_if = "Option::is_none")]
    pub sum: Option<f64>,
    /// The min of all values in the bucket
    #[serde(rename = "min", skip_serializing_if = "Option::is_none")]
    pub min: Option<f64>,
    /// The max of all values in the bucket
    #[serde(rename = "max", skip_serializing_if = "Option::is_none")]
    pub max: Option<f64>,
    /// The 95th percentile
    #[serde(rename = "percentile_95", skip_serializing_if = "Option::is_none")]
    pub percentile_95: Option<f64>,
    /// The organization id
    #[serde(rename = "organization_id", skip_serializing_if = "Option::is_none")]
    pub organization_id: Option<String>,
    /// The organization id
    #[serde(rename = "instance_id", skip_serializing_if = "Option::is_none")]
    pub instance_id: Option<String>,
}

impl Bucket {
    pub fn new() -> Bucket {
        Bucket {
            timestamp: None,
            bucket_size: None,
            average: None,
            sum: None,
            min: None,
            max: None,
            percentile_95: None,
            organization_id: None,
            instance_id: None,
        }
    }
}

/// The size of the bucket
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BucketSize {
    #[serde(rename = "1h")]
    Variant1h,
    #[serde(rename = "1d")]
    Variant1d,
    #[serde(rename = "10m")]
    Variant10m,
}

impl Default for BucketSize {
    fn default() -> BucketSize {
        Self::Variant1h
    }
}

