/*
 * Nile API
 *
 * Making SaaS chill.
 *
 * The version of the OpenAPI document: 0.1.0-fdd7cd5
 * Contact: support@thenile.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateWorkspaceRequest {
    #[serde(rename = "name")]
    pub name: String,
}

impl CreateWorkspaceRequest {
    pub fn new(name: String) -> CreateWorkspaceRequest {
        CreateWorkspaceRequest {
            name,
        }
    }
}


