/*
 * Nile API
 *
 * Making SaaS chill.
 *
 * The version of the OpenAPI document: 0.1.0-fdd7cd5
 * Contact: support@thenile.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateEntityRequest {
    #[serde(rename = "name")]
    pub name: String,
    /// A JSON Schema
    #[serde(rename = "schema")]
    pub schema: serde_json::Value,
}

impl CreateEntityRequest {
    pub fn new(name: String, schema: serde_json::Value) -> CreateEntityRequest {
        CreateEntityRequest {
            name,
            schema,
        }
    }
}


