/*
 * Nile API
 *
 * Making SaaS chill.
 *
 * The version of the OpenAPI document: 0.1.0-fdd7cd5
 * Contact: support@thenile.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Invite {
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "org")]
    pub org: String,
    #[serde(rename = "inviter")]
    pub inviter: String,
    #[serde(rename = "status")]
    pub status: Status,
}

impl Invite {
    pub fn new(code: String, org: String, inviter: String, status: Status) -> Invite {
        Invite {
            code,
            org,
            inviter,
            status,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "active")]
    Active,
}

impl Default for Status {
    fn default() -> Status {
        Self::Active
    }
}

