/*
 * Nile API
 *
 * Making SaaS chill.
 *
 * The version of the OpenAPI document: 0.1.0-fdd7cd5
 * Contact: support@thenile.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListMetricDefinitionsResponse {
    /// The list of metric definitions for a workspace or entity
    #[serde(rename = "metric_definitions")]
    pub metric_definitions: Vec<crate::models::MetricDefinition>,
}

impl ListMetricDefinitionsResponse {
    pub fn new(metric_definitions: Vec<crate::models::MetricDefinition>) -> ListMetricDefinitionsResponse {
        ListMetricDefinitionsResponse {
            metric_definitions,
        }
    }
}


