/*
 * Nile API
 *
 * Making SaaS chill.
 *
 * The version of the OpenAPI document: 0.1.0-fdd7cd5
 * Contact: support@thenile.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LoginInfo {
    /// The email of the user we are authenticating
    #[serde(rename = "email")]
    pub email: String,
    /// The password of the user
    #[serde(rename = "password")]
    pub password: String,
}

impl LoginInfo {
    pub fn new(email: String, password: String) -> LoginInfo {
        LoginInfo {
            email,
            password,
        }
    }
}


