/*
 * Nile API
 *
 * Making SaaS chill.
 *
 * The version of the OpenAPI document: 0.1.0-fdd7cd5
 * Contact: support@thenile.dev
 * Generated by: https://openapi-generator.tech
 */

/// PatchOperation : The JSONPatch operations you would like to apply to the instance


#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "op")]
pub enum PatchOperation {
    #[serde(rename="AddOperation")]
    AddOperation {
        /// The JSON Pointer Path you want to add or replace
        #[serde(rename = "path")]
        path: String,
        /// the value to add or replace
        #[serde(rename = "value")]
        value: serde_json::Value,
        /// The JSON Pointer path you would like to move/copy from
        #[serde(rename = "from")]
        from: String,
    },
    #[serde(rename="CopyOperation")]
    CopyOperation {
        /// The JSON Pointer path you would like to move/copy to
        #[serde(rename = "path")]
        path: String,
        /// the value to add or replace
        #[serde(rename = "value")]
        value: serde_json::Value,
        /// The JSON Pointer path you would like to move/copy from
        #[serde(rename = "from")]
        from: String,
    },
    #[serde(rename="MoveOperation")]
    MoveOperation {
        /// The JSON Pointer path you would like to move/copy to
        #[serde(rename = "path")]
        path: String,
        /// the value to add or replace
        #[serde(rename = "value")]
        value: serde_json::Value,
        /// The JSON Pointer path you would like to move/copy from
        #[serde(rename = "from")]
        from: String,
    },
    #[serde(rename="RemoveOperation")]
    RemoveOperation {
        /// The JSON Pointer path to remove
        #[serde(rename = "path")]
        path: String,
        /// the value to add or replace
        #[serde(rename = "value")]
        value: serde_json::Value,
        /// The JSON Pointer path you would like to move/copy from
        #[serde(rename = "from")]
        from: String,
    },
    #[serde(rename="ReplaceOperation")]
    ReplaceOperation {
        /// The JSON Pointer Path you want to add or replace
        #[serde(rename = "path")]
        path: String,
        /// the value to add or replace
        #[serde(rename = "value")]
        value: serde_json::Value,
        /// The JSON Pointer path you would like to move/copy from
        #[serde(rename = "from")]
        from: String,
    },
}




