/*
 * Nile API
 *
 * Making SaaS chill.
 *
 * The version of the OpenAPI document: 0.1.0-fdd7cd5
 * Contact: support@thenile.dev
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RemoveOperationAllOf {
    /// The JSON Pointer path to remove
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "op", skip_serializing_if = "Option::is_none")]
    pub op: Option<Op>,
}

impl RemoveOperationAllOf {
    pub fn new() -> RemoveOperationAllOf {
        RemoveOperationAllOf {
            path: None,
            op: None,
        }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Op {
    #[serde(rename = "remove")]
    Remove,
}

impl Default for Op {
    fn default() -> Op {
        Self::Remove
    }
}

use serde::{Deserialize, Serialize};
